version: "4"

services:
  web:
    build: .
    container_name: portfolio_web
    command: bash ./bashes/RunBash.sh
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/portfolio/src
      - ./static_volume:/portfolio/static
      - ./media_volume:/portfolio/media
    depends_on:
      - db
    networks:
      - portfolio_network
    env_file:
      - ./.env
  
  db:
    image: postgres:12-alpine
    container_name: portfolio_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=portfoliosecret
      - POSTGRES_DB=portfolio
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    



networks:
  portfolio_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres: