version: "4"

services:
  web:
    build: .
    container_name: portfolio_web
    command: bash ./bashes/RunBash.sh
    restart: always
    volumes:
      - .:/portfolio/src
      - ./static_volume:/portfolio/static
      - ./media_volume:/portfolio/media
    depends_on:
      - db
    networks:
      - portfolio_network
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25.4-alpine
    container_name: portfolio_nginx
    restart: always
    volumes:
      -  ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/portfolio/static
      - media_volume:/portfolio/media
    ports:
      - 8001:80
    depends_on:
      - web
    networks:
      - portfolio_network
  
  db:
    image: postgres:15-alpine
    container_name: portfolio_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=portfoliosecret
      - POSTGRES_DB=portfolio
    volumes:
      - ./portfolio_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    



networks:
  portfolio_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  portfolio_data: